#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED
#define TODO_OK 0
#define ARCHIVO_NO_ENCONTRADO 10
#define NO_SE_PUEDE_CREAR_ARCHIVO 20

#define ERROR 0

#define ERROR_APERTURA_ARCHIVO 100

#define TAM_CABECERA_BMP 2


#endif // CONSTANTES_H_INCLUDED
